import type { Metadata } from 'next'

// export const metadata: Metadata = {
//   title: 'Карандаш',
//   description: 'Generated by create next app',
// }

export default function GildLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      {children}
    </>
  )
}
